#!/bin/bash

if ! hash git 2> /dev/null; then
	echo "Install requires git"
	exit 1
fi

GIT_MAJOR_VERSION=$(git --version | cut -d' ' -f3 | cut -d'.' -f1)

export DOTFILES_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

pushd $DOTFILES_DIR
git pull origin master
git submodule init

if [ $GIT_MAJOR_VERSION -lt "2" ]; then
	git submodule update --recursive
else
	git submodule update --recursive --remote
fi

. makelinks
popd
