#!/bin/bash
cd "${0%/*}"
pip3 install --upgrade pip
pip3 install --upgrade -r requirements.txt
jupyter serverextension enable --py jupyterlab_code_formatter
jupyter labextension install \
  @jupyter-widgets/jupyterlab-manager \
  @ryantam626/jupyterlab_code_formatter \
  @ryantam626/jupyterlab_sublime
