#!/bin/bash

ln -sfv "$DOTFILES_DIR/.oh-my-zsh" ~
ln -sfv "$DOTFILES_DIR/shad-zsh-theme" "$DOTFILES_DIR/.oh-my-zsh/custom/themes"

# vim
ln -sfv "$DOTFILES_DIR/.vimrc" ~

# screen
ln -sfv "$DOTFILES_DIR/.screenrc" ~

# shell
ln -sfv "$DOTFILES_DIR/.sharedrc" ~
ln -sfv "$DOTFILES_DIR/.profile" ~

# zsh
ln -sfv "$DOTFILES_DIR/.zshrc" ~
ln -sfv "$DOTFILES_DIR/.zsh-git-prompt" ~

# bash
ln -sfv "$DOTFILES_DIR/.bashrc" ~
ln -sfv "$DOTFILES_DIR/.bash_profile" ~
ln -sfv "$DOTFILES_DIR/.bash-git-prompt" ~

# git
ln -sfv "$DOTFILES_DIR/.gitconfig" ~
ln -sfv "$DOTFILES_DIR/.gitignore_global" ~
