#!/bin/bash

DOTFILES_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# vim
ln -sfvh "$DOTFILES_DIR/.vimrc" "$HOME"
mkdir -p "$HOME/.vim/autoload"
ln -sfvh "$DOTFILES_DIR/vim-pathogen-master/autoload/pathogen.vim" "$HOME/.vim/autoload/pathogen.vim"
mkdir -p "$HOME/.vim/bundle"
ln -sfvh "$DOTFILES_DIR/vim-bracketed-paste-master" "$HOME/.vim/bundle/vim-bracketed-paste"
ln -sfvh "$DOTFILES_DIR/vim-easymotion-master" "$HOME/.vim/bundle/vim-easymotion"

# screen
ln -sfvh "$DOTFILES_DIR/.screenrc" "$HOME"

# shell
ln -sfvh "$DOTFILES_DIR/.sharedrc" "$HOME"
ln -sfvh "$DOTFILES_DIR/.profile" "$HOME"

# zsh
ln -sfvh "$DOTFILES_DIR/.zshrc" "$HOME"
ln -sfvh "$DOTFILES_DIR/zsh-git-prompt-master" "$HOME/.zsh-git-prompt"
ln -sfvh "$DOTFILES_DIR/oh-my-zsh-master" "$HOME/.oh-my-zsh"
ln -sfvh "$DOTFILES_DIR/.iterm2_shell_integration.zsh" "$HOME"
mkdir -p "$HOME/.oh-my-zsh/custom/plugins"
ln -sfvh "$DOTFILES_DIR/zsh-syntax-highlighting-master" "$HOME/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting"
mkdir -p "$HOME/.oh-my-zsh/custom/themes"
ln -sfvh "$DOTFILES_DIR/shad.zsh-theme" "$HOME/.oh-my-zsh/custom/themes"

# bash
ln -sfvh "$DOTFILES_DIR/.bashrc" "$HOME"
ln -sfvh "$DOTFILES_DIR/.bash_profile" "$HOME"
ln -sfvh "$DOTFILES_DIR/bash-git-prompt-master" "$HOME/.bash-git-prompt"
ln -sfvh "$DOTFILES_DIR/.iterm2_shell_integration.bash" "$HOME"

# git
ln -sfvh "$DOTFILES_DIR/.gitconfig" "$HOME"
ln -sfvh "$DOTFILES_DIR/.gitignore_global" "$HOME"

# bin
mkdir -p "$HOME/.local/bin"
ln -sfvh "$DOTFILES_DIR/rmate-master/rmate" "$HOME/.local/bin/rmate"
ln -sfvh "$DOTFILES_DIR/.local/bin/autotail" "$HOME/.local/bin/autotail"
